export const CRYPTOCURRENCIES: { name: string; ticker: string; coingeckoId: string }[] = [
    { name: 'Bitcoin', ticker: 'BTC', coingeckoId: 'bitcoin' },
    { name: 'Ethereum', ticker: 'ETH', coingeckoId: 'ethereum' },
    { name: 'Tether', ticker: 'USDT', coingeckoId: 'tether' },
    { name: 'BNB', ticker: 'BNB', coingeckoId: 'binancecoin' },
    { name: 'Solana', ticker: 'SOL', coingeckoId: 'solana' },
    { name: 'USD Coin', ticker: 'USDC', coingeckoId: 'usd-coin' },
    { name: 'XRP', ticker: 'XRP', coingeckoId: 'ripple' },
    { name: 'Dogecoin', ticker: 'DOGE', coingeckoId: 'dogecoin' },
    { name: 'Toncoin', ticker: 'TON', coingeckoId: 'the-open-network' },
    { name: 'Cardano', ticker: 'ADA', coingeckoId: 'cardano' },
    { name: 'Shiba Inu', ticker: 'SHIB', coingeckoId: 'shiba-inu' },
    { name: 'Avalanche', ticker: 'AVAX', coingeckoId: 'avalanche-2' },
    { name: 'TRON', ticker: 'TRX', coingeckoId: 'tron' },
    { name: 'Polkadot', ticker: 'DOT', coingeckoId: 'polkadot' },
    { name: 'Bitcoin Cash', ticker: 'BCH', coingeckoId: 'bitcoin-cash' },
    { name: 'Chainlink', ticker: 'LINK', coingeckoId: 'chainlink' },
    { name: 'Polygon', ticker: 'MATIC', coingeckoId: 'matic-network' },
    { name: 'Near Protocol', ticker: 'NEAR', coingeckoId: 'near' },
    { name: 'Litecoin', ticker: 'LTC', coingeckoId: 'litecoin' },
    { name: 'Uniswap', ticker: 'UNI', coingeckoId: 'uniswap' },
    { name: 'Pepe', ticker: 'PEPE', coingeckoId: 'pepe' },
    { name: 'Kaspa', ticker: 'KAS', coingeckoId: 'kaspa' },
    { name: 'Ethereum Classic', ticker: 'ETC', coingeckoId: 'ethereum-classic' },
    { name: 'Dai', ticker: 'DAI', coingeckoId: 'dai' },
    { name: 'Aptos', ticker: 'APT', coingeckoId: 'aptos' },
    { name: 'Monero', ticker: 'XMR', coingeckoId: 'monero' },
    { name: 'Render', ticker: 'RNDR', coingeckoId: 'render-token' },
    { name: 'Hedera', ticker: 'HBAR', coingeckoId: 'hedera-hashgraph' },
    { name: 'Stellar', ticker: 'XLM', coingeckoId: 'stellar' },
    { name: 'Cosmos', ticker: 'ATOM', coingeckoId: 'cosmos' },
    { name: 'Arbitrum', ticker: 'ARB', coingeckoId: 'arbitrum' },
    { name: 'OKB', ticker: 'OKB', coingeckoId: 'okb' },
    { name: 'Filecoin', ticker: 'FIL', coingeckoId: 'filecoin' },
    { name: 'Immutable', ticker: 'IMX', coingeckoId: 'immutable-x' },
    { name: 'Cronos', ticker: 'CRO', coingeckoId: 'crypto-com-chain' },
    { name: 'VeChain', ticker: 'VET', coingeckoId: 'vechain' },
    { name: 'Injective', ticker: 'INJ', coingeckoId: 'injective-protocol' },
    { name: 'Sui', ticker: 'SUI', coingeckoId: 'sui' },
    { name: 'The Graph', ticker: 'GRT', coingeckoId: 'the-graph' },
    { name: 'Optimism', ticker: 'OP', coingeckoId: 'optimism' },
    { name: 'Bittensor', ticker: 'TAO', coingeckoId: 'bittensor' },
    { name: 'Arweave', ticker: 'AR', coingeckoId: 'arweave' },
    { name: 'Celestia', ticker: 'TIA', coingeckoId: 'celestia' },
    { name: 'Fantom', ticker: 'FTM', coingeckoId: 'fantom' },
    { name: 'Theta Network', ticker: 'THETA', coingeckoId: 'theta-token' },
    { name: 'Lido DAO', ticker: 'LDO', coingeckoId: 'lido-dao' },
    { name: 'Aave', ticker: 'AAVE', coingeckoId: 'aave' },
    { name: 'Algorand', ticker: 'ALGO', coingeckoId: 'algorand' },
    { name: 'Maker', ticker: 'MKR', coingeckoId: 'maker' },
    { name: 'Sei', ticker: 'SEI', coingeckoId: 'sei-network' },
    { name: 'dogwifhat', ticker: 'WIF', coingeckoId: 'dogwifhat' }
];